#!/bin/bash

source <(otc-task-include lib/filesystem.sh)
source <(otc-task-include lib/helm.sh)
source <(otc-task-include lib/assert.sh)
source <(otc-task-include lib/console.sh)

# Param helm_dir - Helm chart directory
# Param namespace
function main
{
	local helm_dir="$1"
	local namespace="$2"
	local custom_name="$3" #optional

	assert-not-empty helm_dir
	assert-not-empty namespace
	
	local release_name_file=$(mktemp -t "release_name-XXXXXXXX")
	local helm_deploy_success=false

	helm-deploy "$helm_dir" "$namespace" "$custom_name" \
		> $release_name_file && helm_deploy_success=$?

	local release_name=$(cat $release_name_file)
	
	if [ -z "$release_name" ]
	then
		red "Could not get release name." >&2
		echo $HELM_GENERAL_DEPLOY_ERROR_MESSAGE >&2

		exit 109
	fi

	rm $release_name_file

	if ! $helm_deploy_success
	then
		local history_count=$(($(helm history $release_name | wc -l) - 1))

		if ! echo $history_count | egrep '^[0-9]+$' > /dev/null 2>&1
		then
			red "CRITICAL ERROR" >&2
			echo "Could not get history for '$release_name'. At this point, release '$release_name' " >&2
			echo "should exists, neither it successfully deployed or not." >&2
			echo $HELM_GENERAL_DEPLOY_ERROR_MESSAGE >&2

			exit 117
		fi

		if [ "$history_count" -gt "0" ]
		then
			red "As helm deploy failed, rolling back to previous revision." >&2
			assert-success helm rollback $release_name 0 >&2
		else
			red "Seems that is the first '$release_name' release." >&2
			red "As helm deploy has failed, going to deleting it." >&2
			assert-success helm delete $release_name --purge >&2
		fi
	fi

	exit $helm_deploy_success
}

main "$@"