#!/bin/bash

source <(otc-task-include lib/filesystem.sh)
source <(otc-task-include lib/helm.sh)
source <(otc-task-include lib/assert.sh)
source <(otc-task-include lib/console.sh)

# Param helm_dir - Helm chart directory
# Param namespace
# Look for ENVIRONMENT_NAME environment var
function main
{
	local helm_dir="$1"
	local namespace="$2"
	local custom_name="$3" #optional

	assert-not-empty helm_dir
	assert-not-empty namespace
	
	local release_name_file=$(mktemp -t "release_name-XXXXXXXX")
	local helm_deploy_status_code=0 # assume success

	local custom_value=''

	if ! [ -z "$ENVIRONMENT_NAME" ]
	then
		custom_value="$(echo $ENVIRONMENT_NAME | awk '{ print tolower($0) }')-values.yaml"
		echo "Using '$custom_value' as helm values." >&2
	fi

	helm-deploy "$helm_dir" "$namespace" "$custom_name" "$custom_value" \
		> $release_name_file || helm_deploy_status_code=$?

	if [ "$helm_deploy_status_code" -eq "$HELM_DEPLOY_CUSTOM_VALUES_FILE_NOT_FOUND" ]
	then
		echo "----------------------------------------------------------------------------------------------------------------" >&2
		echo "O arquivo com os valores para o ambiente '$ENVIRONMENT_NAME' nao foi encontrado, logo nao sera possivel realizar" >&2
		echo "o deploy neste ambiente." >&2
		echo "Para corrigir este problema, adicione o arquivo '$custom_value' no diretorio do helm chart (normalmente Kubernetes.Helm)." >&2
		echo "" >&2
		echo "IMPORTANTE: Dados sensiveis, como strings de conexao, credenciais para servicos externos, etc, nao devem ser inseridos" >&2
		echo "==========  neste arquivo. Para isso, deverao ser utilizados secrets (em caso de dúvidas, conversar com " >&2
		echo "            arquitetura/infra-estrutura)." >&2
		echo "----------------------------------------------------------------------------------------------------------------" >&2
		echo '{ "Level": "Error", "Message": "teste" }' >> /proc/1/fd/1
		exit 103
	fi

	local release_name=$(cat $release_name_file)
	
	if [ -z "$release_name" ]
	then
		red "Could not get release name." >&2
		echo $HELM_GENERAL_DEPLOY_ERROR_MESSAGE >&2

		exit 109
	fi

	rm $release_name_file

	if [ "$helm_deploy_status_code" -ne "0" ]
	then
		local history_count=$(($(helm history $release_name | wc -l) - 1))

		if ! echo $history_count | egrep '^[0-9]+$' > /dev/null 2>&1
		then
			red "Could not get history for '$release_name'. At this point, release '$release_name' " >&2
			red "should exists, neither it successfully deployed or not." >&2
			echo $HELM_GENERAL_DEPLOY_ERROR_MESSAGE >&2

			exit 117
		fi

		if [ "$history_count" -gt "0" ]
		then
			red "As helm deploy failed, rolling back to previous revision." >&2
			assert-success helm rollback $release_name 0 >&2
		else
			red "Seems that is the first '$release_name' release." >&2
			red "As helm deploy has failed, going to deleting it." >&2
			assert-success helm delete $release_name --purge >&2
		fi
	fi

	exit $helm_deploy_status_code
}

main "$@"