#!/bin/bash

set -e

source <(otc-task-include lib/git.sh)
source <(otc-task-include lib/assert.sh)
source <(otc-task-include lib/vsts.sh)
source <(otc-task-include lib/console.sh)
source <(otc-task-include lib/azure-pipelines-yaml-protection.sh)
source <(otc-task-include lib/vsts-pr-statuses.sh)

# Param lines_threshold
# Param lines_include_pattern (optional)
# Param lines_exclude_pattern (optional)
# Required environment variables:
#  - SYSTEM_PULLREQUEST_PULLREQUESTID
function size-validation
{
	local lines_threshold=$1
	local lines_include_pattern="$2"
	local lines_exclude_pattern="$3"
	assert-not-empty lines_threshold
	assert-not-empty SYSTEM_PULLREQUEST_PULLREQUESTID
	local pullrequest_id=$SYSTEM_PULLREQUEST_PULLREQUESTID
	local lines_changed=$(count-changed-lines $(get-base-branch) \
		"$pullrequest_id" "$lines_include_pattern" "$lines_exclude_pattern")
	local status='succeeded'
	if [ "$lines_changed" -gt "$lines_threshold" ]
	then
		status='failed'		
		red "Pull request size ($lines_changed lines) exceeds threshold ($lines_threshold)."
	fi
	pullrequest-set-size-status "$pullrequest_id" "$status" "$lines_changed" "$lines_threshold"
}

# Param pullrequest_id
function show-modified-items
{
	local pullrequest_id="$1"
	assert-not-empty pullrequest_id
	echo "Modified items without filter:"
	echo "Add	Rem"
	git-diff $(get-base-branch) "$pullrequest_id"	
}

assert-not-empty SYSTEM_PULLREQUEST_PULLREQUESTID
reset-pr-statuses $SYSTEM_PULLREQUEST_PULLREQUESTID
show-modified-items $SYSTEM_PULLREQUEST_PULLREQUESTID
azure-pipelines-yaml-protection
exit 1
size-validation "$@"

