#!/bin/bash

set -e

source <(otc-task-include lib/git.sh)
source <(otc-task-include lib/assert.sh)
source <(otc-task-include lib/vsts.sh)
source <(otc-task-include lib/console.sh)

function pullrequest-set-size-status
{
	local pullrequest_id="$1"
	local state="$2"
	assert-not-empty pullrequest_id
	assert-not-empty state
	vsts-pr-push-status \
		"$pullrequest_id" \
		"preconditions" \
		"size" \
		"$state" \
		"https://arquitetura.oleconsignado.com.br/checklist-pull-request/#Tamanho-do-PR"> /dev/null	
}

function pullrequest-set-preconditions-status
{
	local pullrequest_id="$1"
	local state="$2"
	assert-not-empty pullrequest_id
	assert-not-empty state
	vsts-pr-push-status \
		"$pullrequest_id" \
		"preconditions" \
		"generic" \
		"$state" > /dev/null	
}

function get-base-branch
{
	assert-not-empty SYSTEM_PULLREQUEST_TARGETBRANCH
	echo "$SYSTEM_PULLREQUEST_TARGETBRANCH" | sed 's/^refs\/heads\///'
}

# Param lines_threshold
# Param lines_include_pattern (optional)
# Param lines_exclude_pattern (optional)
# Required environment variables:
#  - SYSTEM_PULLREQUEST_TARGETBRANCH
function size-validation
{
	local lines_threshold=$1
	local lines_include_pattern="$2"
	local lines_exclude_pattern="$3"
	assert-not-empty lines_threshold
	assert-not-empty SYSTEM_PULLREQUEST_TARGETBRANCH
	assert-not-empty SYSTEM_PULLREQUEST_PULLREQUESTID
	local pullrequest_id=$SYSTEM_PULLREQUEST_PULLREQUESTID
	local lines_changed=$(count-changed-lines $(get-base-branch) \
		"$pullrequest_id" "$lines_include_pattern" "$lines_exclude_pattern")
	if [ "$lines_changed" -gt "$lines_threshold" ]
	then
		pullrequest-set-size-status "$pullrequest_id" "failed"
		red "Pull request size ($lines_changed lines) exceeds threshold ($lines_threshold)."
	else
		pullrequest-set-size-status "$pullrequest_id" "succeeded"
		green "Pull Request size validation passed."
	fi
}

function azure-pipelines-yaml-protection
{
	local pullrequest_id=$SYSTEM_PULLREQUEST_PULLREQUESTID
	if git-diff $(get-base-branch) $pullrequest_id | egrep '^[0-9] +[0-9] +azure-pipelines\.yaml$' 
	then
		pullrequest-set-preconditions-status $pullrequest_id "failed"
		red "******************************************************************"
		red "* azure-pipelines.yaml should not been modified in topic branch. *"
		red "******************************************************************"
		exit 47 # Critical, pipeline must not procceed.
	fi

	pullrequest-set-preconditions-status $pullrequest_id "succeeded"
}

azure-pipelines-yaml-protection
size-validation "$1" "$2" "$3"
