#!/bin/bash

source <(otc-task-include lib/assert.sh)
source <(otc-task-include lib/console.sh)
source <(otc-task-include lib/filesystem.sh)
source <(otc-task-include lib/sonar.sh)

sonar-scanner-begin "${BUILD_SOURCESDIRECTORY}/Source" "$COMMON_TESTRESULTSDIRECTORY"